name: budget_tracker_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  injectable: 2.1.2
  get_it: 7.6.0
  provider: 6.0.5
  auto_route: 7.8.0
  json_serializable: 6.7.1
  shared_preferences: 2.2.2
  hydrated_bloc: 9.0.0
  freezed_annotation: 2.4.1
  equatable: 2.0.5
  flutter_bloc: 8.1.4
  path_provider: 2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  build_runner: 2.4.6
  flutter_gen_runner: 5.3.1
  injectable_generator: 2.1.6
  auto_route_generator: 7.3.0
  freezed: 2.4.1
  freezed_annotation: 2.4.1
  percent_indicator: 4.2.3

flutter:
  uses-material-design: true

